#!/usr/bin/env bash
# this script  transfers a file from our client to a server

# $1 is the path to the file to be transferred
# $2 is IP of the server we want to transfer the file to
# $3 is the username scp connects with
# $4 path to the SSH private key that scp uses

if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -eq 3 ]
then
    scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/.
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/.
fi
