#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Counter variable
counter=0

# Using an until loop to dispaly "Best School" 10 times
until [ $counter -ge 10 ]
do
echo "Best School"
# Increament the counter
((counter++))
done
