#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Counter variables
counter=0

# Using a while loop to display "Best School" 10 times
while [ $counter -lt 10 ]
do
if [ $counter -eq 8 ]; then
echo "Best School"
echo "Hi"
else
echo "Best School"
fi

# Increment the counter
((counter++))
done
