#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Counter variable
counter=1

# Using a while loop to loop from 1 to 20
while [ $counter -le 20 ]
do
	case $counter in
		4)
			echo "$counter"
			echo "bad luck from china"
			;;
		9)
			echo "$counter"
			echo "bad luck from japan"
			;;
		17)
			echo "$counter"
			echo "bad luck from italy"
			;;
		*)
			echo "$counter"
			;;
	esac

	# Increment the counter
	((counter++))
done
