#!/usr/bin/env bash
# script that gives you information about the school file

# Defines the filename 
filename="school"

# Check if the file exist
if [ -e "$filename" ]; then
echo "school file exists"


# check if the file is empty
if [ -s "$filename" ]; then
echo "school file is not empty"
else
echo "school file is empty"
fi

# Check if the file is a regular file
if [ -f "$filename" ]; then
echo "school is a regular file"
fi
else
echo "school file does not exist"
fi
