#!/usr/bin/env bash
# Configures an ubuntu server as follows:
# Localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/host.new
echo "8.8.8.8		facebook.com >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
