#!/usr/bin/env bash
# Displays all active IPv4 addresses on the machine.

# Checks if ip command is available
if ! command -v ip &> /dev/null; then
	echo "Error: ip command not found. This script requires the ip command to be installed ." >&2
	exit 1
fi

# Display all active IPv4 addresses
ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}'
